### ISSUE TITLE
Logo issue.

### ISSUE THREAD

**Issue by hblankenship** [OWASP/www-project-top-10-low-code-no-code-security-risks#53]
The logo usage here is in violation of the policy:
"Questionable practices include changing the circle to a square, altering the angle of the wasp feature, using non-branded wasp images, copyrighted images, and any other treatment that alters or obscures the OWASP brand. The OWASP Foundation reserves the right to request changes to any graphic that does not comply with these rules."

Please see https://owasp.org/www-policy/operational/branding for more information.

**Comment by mbrg** [comment]
Hi @hblankenship, thank you for spotting this. I've removed the logo and will reach out after we've fully implemented the guidelines.
